#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

source $XDG_CONFIG_HOME/bspwm/panel/panel.cfg

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

$HOME/local/bin/info > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | $XDG_CONFIG_HOME/bspwm/panel/panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$FONT2" -f "$FONT1" -F $COLOR_FOREGROUND -B $COLOR_BACKGROUND -u $UNDERLINE_WIDTH&

wait
