#!/bin/sh
#
# ~/.xinitrc
#
# Executed by `startx` (run your window manager from here)

#maybe will need this
#if [ ! "$DBUS_SESSION_BUS_ADDRESS" ] && have dbus-launch; then
#    exec dbus-launch --exit-with-session ~/.xinitrc "$@" || exit
#fi

source_checked() {
    local file=$1
    [[ -f $file ]] && source "$file"
}

# Import DISPLAY and XAUTHORITY into the systemd --user environment.
source_checked /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

xsetroot -cursor_name X_cursor

setxkbmap -layout br,ru -variant ,phonetic -option grp:menu_toggle,compose:caps
ponymix unmute &
dunst -config "${XDG_CONFIG_HOME:-$HOME/local/cfg}"/dunst/dunstrc & # dunst only looks into .config/dunst
xsetroot -mod 16 16 -fg '#343d46' -bg '#2b303b'

if ! [ "$(pgrep emacs)" ]
then
  emacs --daemon &
fi

read_doc create-db &

sxhkd &
#exec bspwm -c ${XDG_CONFIG_HOME:-$HOME/local/cfg}/bspwm/bspwmrc
#dwm_status &
#exec dwm &> ~/local/tmp/log/dwm.log
# xmodmap "${XDG_CONFIG_HOME:-$HOME/local/cfg}/x11/xmodmap" # When using stump
# stumpwm
mkdir -p "${XDG_RUNTIME_DIR:-/tmp/}"/x11/fs
x11fs "${XDG_RUNTIME_DIR:-/tmp/}"/x11/fs
exec swm &> "${XDG_CACHE_HOME:-HOME/local/tmp}"/log/swm.log
