#!/bin/sh --
#
# XDG_CONFIG_HOME/x11/xinitrc
#
# Executed by `startx` (run your window manager from here)

#maybe will need this
if [ ! "$DBUS_SESSION_BUS_ADDRESS" ] && have dbus-launch; then
    exec dbus-launch --exit-with-session "${XDG_CONFIG_HOME:-$HOME/local/cfg}"/x11/xinitrc "$@" || exit
fi

source_checked() {
    local file=$1
    [[ -f $file ]] && source "$file"
}

# Import DISPLAY and XAUTHORITY into the systemd --user environment.
source_checked /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

xsetroot -cursor_name X_cursor
setxkbmap -option grp:menu_toggle,compose:caps
#xsetroot -mod 16 16 -fg '#343d46' -bg '#2b303b'
xsetroot -solid '#1a1b26'

pactl set-sink-mute alsa_output.pci-0000_00_1b.0.analog-stereo 0

dunst &

log_dir="$HOME"/local/var/log/i3
mkdir -p "$log_dir"
exec i3 &>"$log_dir"/wm.log
