" home/.vim/vimrc

let local=$HOOME.'/local/'
let data=local.'/share/vim'
let cfg=local.'/cfg/vim/'
set undodir=data/undo
set directory=data/swap
set backupdir=data/backup
set viminfofile=$HOME/.vim/data/viminfo

call mkdir(&backupdir, "p")
call mkdir(&directory, "p")
call mkdir(&undodir, "p")


syntax on
filetype indent plugin on

set title
set number
set hidden
set backup 
set showcmd
set autoread
set undofile 
set wildmenu
set linebreak
set smartcase
set scrolloff=2
set colorcolumn=81
set cinoptions+=t0

set cursorline
set expandtab
set tabstop=4
set shiftwidth=4

set wildignore=*.pyc,*\~,*.o,*.obj
set vb              " visual bell
set spelllang=en_us

let g:tar_cmd = 'bsdtar'
let g:tar_secure = 1
autocmd BufReadCmd *.iso,*.rar,*.7z call tar#Browser(expand("<amatch>"))

colorscheme torte

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/local/share/vim/plugins')
Plug 'https://github.com/sirver/UltiSnips'
" let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsSnippetDirectories=['/home/kotto/local/cfg/nvim/UltiSnips/']
" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"
call plug#end()
