#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

source ~/.config/bspwm/panel/profile
source ~/.config/bspwm/panel/panel.cfg

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
~/.config/bspwm/panel/info.sh > "$PANEL_FIFO" &



cat "$PANEL_FIFO" | ~/.config/bspwm/panel/panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$FONT2" -f "$PANEL_FONT_FAMILY1" -f "$ICON_FONT" -F $COLOR_FOREGROUND -B $COLOR_BACKGROUND &

wait
