#! /bin/sh

bspc config border_width        5
bspc config window_gap          0
bspc config top_padding         20

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config ignore_ewmh_focus           true
bspc config pointer_follows_monitor     true
bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true
bspc config focused_border_color        "#0D497B"
bspc config external_rules_command ~/.config/bspwm/external_rules

bspc rule -a Gimp desktop=^7 follow=on floating=off
bspc rule -a Firefox desktop=^1
bspc rule -a mpv desktop=^8 floating=false focus=off
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=on
bspc rule -a Steam desktop=^4 split_dir=off
bspc rule -a dota2 desktop=^5 fullscreen=on folow=off
bspc rule -a Skype desktop=^3 floating=true follow=off
bspc rule -a laucher desktop=^3 floating=true


~/.config/bspwm/panel/panelrc &
