colorscheme base16_default

set global tabstop 2
set global aligntab false
set global indentwidth 0
set global scrolloff 3,5
set global incsearch true

set global modelinefmt 'face volatile %sh<git branch | awk \'/^\*/ {print "git:"$2}\'> %opt{filetype} %val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}} - %val{client}@[%val{session}]'

hook global WinSetOption filetype=(?!makefile|vbs|batch).* %{
    echo hi
    hook global InsertChar \t %{
      exec -draft -itersel h@
    }
}

hook global NormalKey [/?*nN]|<a-[/?*nN]> %{ try %{
  add-highlighter dynregex '%reg{/}' 0:search
}}

hook global NormalKey <esc> %{ try %{
  remove-highlighter dynregex_%reg{<slash>}
}}

set global ignored_files '.*\.o|.*\.pyc|.*\~|^\#.*\#|.*\.obj|\.git'

hook global WinCreate .* %{
    addhl show_matching
    addhl number_lines
}

map global normal '#' :comment-line<ret>
map global normal '<a-#>' :comment-block<ret>

map global normal   <c-w>   :tmux-new-horizontal<ret>
map global normal   <c-e>   :tmux-new-vertical<ret>
map -docstring 'Search word in `man <word>`' global user k :man<ret> 
# #
# ^
# -
# _
# =
# +
map global user P '!xsel --output --clipboard<ret>' -docstring 'Paste before'
map global user p '<a-!>xsel --output --clipboard<ret>' -docstring 'Paste after'

def ide %{
    rename-client main
    set global jumpclient main

    tmux-new-horizontal rename-client docs
    set global docsclient docs

    tmux-new-vertical rename-client tools
    set global toolsclient tools

    %sh{tmux select-pane -t :.+}
}

set global ui_options ncurses_assistant=dilbert

hook global WinSetOption filetype=c %{
    %sh{
        switches="-std=c11 -Werror -Wextra -Wall -Wno-unused-parameter -Wno-missing-field-initializers"
        if [[ $PWD =~ /home/kotto/dev/c/gui-playground/ ]]; then
            switches="$switches -I/usr/include/freetype2"
        elif [[ $PWD =~ /home/kotto/dev/c/atmega ]]; then
           printf "set buffer clang_options '%s'\n" "$switches"
        elif [[ $PWD =~ /home/kotto/dev/c/ ]]; then
           printf "set buffer clang_options '%s'\n" "$switches"
        elif [[ $PWD =~ /home/kotto/dev/arm/stm/f1 ]]; then
           switches="$switches -I/home/kotto/dev/arm/stm/f1/stm32/device/"
        elif [[ $PWD =~ /home/kotto/dev/arm/stm/f4 ]]; then
           switches="$switches -I/home/kotto/dev/arm/stm/f4/stm32/device/"
        else
           #switches="$switches -fsanitize=address -fsanitize=undefined"
       fi
       printf "set buffer clang_options '%s'\n" "$switches"
    }
}
hook global WinSetOption filetype=(c|cpp) %{
    clang-enable-autocomplete 
    clang-enable-diagnostics
    set buffer tabstop 2
    alias window lint clang-parse
    alias window lint-next clang-diagnostics-next
    hook global BufWritePost .* lint
    map global normal <a-m> :make
    map global normal <a-n> :make-next-error<ret>
    map global normal <a-p> :make-previous-error<ret>
    map global normal <a-N> :lint-next<ret><ret>
}

hook global WinSetOption filetype=python %{
    jedi-enable-autocomplete
    flake8-enable-diagnostics
    alias window lint flake8-lint
    alias window lint-next flake8-diagnostics-next
    %sh{
        if [ $PWD = "/home/mawww/prj/kakoune/src" ]; then
           echo "set buffer jedi_python_path '/usr/share/gdb/python'"
           echo "set buffer path './:/usr/share/gdb/python'"
        fi
    }
}

hook global WinSetOption filetype=(asciidoc) %{
    addhl wrap # softwrap
    hook buffer BufWritePost .* %{
        %sh{asciidoctor $kak_buffile}
    }
}

hook global BufCreate (.*/)?PKGBUILD %{
    set buffer filetype sh
}

hook global WinSetOption filetype=pascal %{
    map buffer object c :begin,end<ret> -docstring 'Pascal/Delphi begin/end block'
    lint-enable
}

hook global WinSetOption filetype=ada %{
    map buffer object c :begin,end<ret> -docstring 'Ada begin/end block'
}

hook global WinSetOption filetype=(batch|vbs|vb) %{
    set buffer eolformat crlf
}
